name: deploy-on-hetzner 
on: push
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: multiple command
          uses: appleboy/ssh-action@v1
          with:
            host: krc-coding.dk
            username: www-data
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              whoami
              ls -al
